# Generated by Django 2.1.5 on 2019-11-17 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(14, 41, 51, 778664)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 14, 41, 51, 778574)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.time(14, 41, 51, 778597)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/main_app/images'),
        ),
    ]
