# Generated by Django 2.2.6 on 2019-11-17 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191117_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(21, 58, 24, 54545)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 21, 58, 24, 54545)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.time(21, 58, 24, 54545)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
