# Generated by Django 2.1.5 on 2019-11-18 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191118_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image_url',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(6, 28, 37, 722410)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 6, 28, 37, 722373)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.time(6, 28, 37, 722392)),
        ),
    ]
